
replicas: 11
region: eu-central-1
registry: k8s.servicenow.io

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 31220
  
image:
  repository: bookmyapp
  tag: dev
  pullPolicy: Always

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: reservation.xmes.bot
      paths: []
  tls: []


serviceAccount:
  create: false
  name: reservation-server

resources: # {}

  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

