
region: us-east-1
replicas: 10

image:
  registry: k8s.servicenow.io
  repository: bookmyapp
  tag: dev
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 32000

resources: 
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

